### ISSUE TITLE
Fix problem with inverted vectors

### ISSUE THREAD

**Issue by Onikiro** [admiralWoop/ASCIIGameEngine#16]
Somewhere x is uses as y, somewhere x + 1 is below than x. It's confusing.
Also fix static Vectors:
Right should be (1, 0);
Left should be (-1, 0);

It's okay that down is (0, 1), because axes are inverted in windows console.

**Comment by Onikiro** [comment]
Probably we should add logical axes and physical axes, where physical axes will be inverted.

**Comment by realwoopee** [comment]
What if we make Y go up, and X go right, and just transform the rendered buffer?

**Comment by realwoopee** [comment]
I'll implement my idea and submit a PR for further discussion
